# Generated by Django 4.0.6 on 2022-07-06 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses_app', '0003_alter_course_options_alter_course_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('F', 'female'), ('M', 'male')], max_length=2)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses_app.course')),
            ],
            options={
                'ordering': ['first_name'],
                'unique_together': {('first_name', 'last_name', 'date_of_birth', 'phone_number', 'email', 'gender', 'course')},
            },
        ),
    ]
